### ISSUE TITLE
repository failed to get version higher than current stored version in repo

### ISSUE THREAD

**Issue by avihoo** [mathcamp/pypicloud#42] opened 2015-02-26 09:50 UTC
Hi,

I encountered an issue, when I have for example, application called app with version 0.1 on my pypicloud repository, and I'm asking to download app with version other than 0.1 that does not exists on the pypi repo, instead of fetching it from the world's pypi repo, I get an error saying the package is not found.

Using pypicloud version 0.2.7 with fallback = cache and S3 storage.

Thanks.

**Comment by johtso** [comment] 2015-02-26 16:56
It seems that if there is *any* version of a package cached, then pypicloud does not fetch the different version of a package if you request it.

This just bit us too.

**Comment by stevearc** [comment] 2015-02-26 17:55
This is somewhat by design, and somewhat a limitation of pip. Let's take the following case:

<table>
  <thead>
    <tr>
      <th>pypicloud</th>
      <th>world pypi</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>mypackage 0.1</td>
      <td>mypackage 0.1</td>
    </tr>
    <tr>
      <td></td>
      <td>mypackage 0.2</td>
    </tr>
  </tbody>
</table>

When you do a `pip install mypackage`, the desired behavior is for it to install version `0.1`. If you're deploying software to internal servers, you don't want your library versions to change just because the maintainer released a new version upstream, you want consistency. In this case, pip requests the list of packages, pypicloud says "I have 0.1", and pip selects 0.1 as the best candidate.

But what happens when you do `pip install mypackage>0.1`? Pip doesn't tell pypicloud that it needs a version *other* than 0.1. It doesn't tell pypicloud anything. All it does is request all package versions for `mypackage`, and then pip handles the version selection. This is the problem you've encountered. Unfortunately there is no way for pypicloud to handle this without breaking the above behavior.

There are a few options for where to go from here. There should be a "fetch" button on the web interface that will allow you to grab additional packages from upstream. You can also use the [http api](http://pypicloud.readthedocs.org/en/latest/topics/api.html#post-api-fetch) You can use this to acquire the packages you need, but it is a manual process (by design).

You can specify the fallback url with pip: `pip install --index-url http://my.pypicloud.com/simple/ --extra-index-url http://pypi.python.org/simple`. Apart from the obvious downside, this also means that if pypicloud doesn't have the desired package version, pip will fetch it directly from pypi and not cache it in pypicloud.

If this is a common desired behavior, I could add an operating mode that would always allow you to download any package version that is available at the world url. I don't think that this would be any more useful than providing the `--extra-index-url` to pip, though.

**Comment by avihoo** [comment] 2015-03-01 06:19
Hi,

Firstly, thank you for the quick responding.
Second, its a feature I do need in my company, because pypicloud repository for us is a way to have our most common packages we use and our internal packages we built to be available locally without the need to search via external repositories, and when we do want to use mypackage > 0.1 we expect pypi to check it internal repo, and when failed to do so, try fetching it from the fallback url it is configured to.

The reason we don't want to use the extra url parameter is because we don't and can't verify that evey user of us is providing these parameters each time he is using pip (some of our installations are automatic and we don't want to go back to all of our codes to change it).
Is there any chance to release a version that will include this feature like we talked? It would be incredibly valuable for us.

Thanks in advance,
Avihoo.

**Comment by stevearc** [comment] 2015-03-02 21:35
Is there a reason why the behavior for `fallback = redirect` is unsuitable for your needs?

**Comment by avihoo** [comment] 2015-03-03 07:23
Hmm, besides that we want to be local repository not always based on world pypi that is not always stable and available, there is no specific reason..

**Comment by stevearc** [comment] 2015-03-04 23:47
Okay, well I'll look into adding a `mirror` mode, but until I get there you should be able to get mostly reasonable behavior by using `fallback = redirect`. Or by setting it to `cache`, installing/fetching packages, and then switching back to `redirect`.

**Comment by avihoo** [comment] 2015-03-05 07:01
Cool, I will use that solution for now.

Thanks

**Comment by avihoo** [comment] 2015-05-12 06:33
Thanks !

**Comment by avihoo** [comment] 2015-05-12 09:20
Seems like after configuring mirror i'm still getting 404 when trying to pip install my-pacage==specific-version

**Comment by stevearc** [comment] 2015-05-12 17:08
Can you give me more information? Is `my-package` something that exists in the fallback pypi? What do you see when you visit `http://your-server/simple/my-package`? When you pip install, are you logged in as a user with write permissions? Are there any copies of `my-package` currently uploaded to pypicloud?

**Comment by avihoo** [comment] 2015-05-13 05:39
Yes, sure.

let's take for example the package 2mp4 (which is in the fallback pypi which is the world's wide pypi http://pypi.python.org/simple)

I set the config to:
pypi.fallback = mirror
pypi.fallback_url = http://pypi.python.org/simple
pypi.cache_update = authenticated

pypi.storage = s3
storage.access_key = ***
storage.secret_key = ***
storage.bucket = my-bucket
storage.prefix = my-prefix/

pypi.db = redis
db.url = redis://root:root@localhost:SOME-PORT/0


Now, I have in my local repo versions 0.1.4 and 0.1.3 of 2mp4.
When doing pip install 2mp4 without version i'm getting

$ ve/bin/pip install 2mp4
You are using pip version 6.0.6, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting 2mp4
  This repository located at pypi.myhost.com is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host pypi.myhost.com.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  Downloading http://pypi.myhost.com/api/package/2mp4/2mp4-0.2.1.tar.gz
Collecting sh (from 2mp4)
  This repository located at pypi.myhost.com is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host pypi.myhost.com'.
  HTTP error 404 while getting http://pypi.myhost.com/api/package/sh/sh-1.11.tar.gz (from http://pypi.myhost.com/pypi/sh/)
  Could not install requirement sh (from 2mp4) because of error 404 Client Error: Not Found
  Could not install requirement sh (from 2mp4) because of HTTP error 404 Client Error: Not Found for URL http://pypi.myhost.com/api/package/sh/sh-1.11.tar.gz (from http://pypi.myhost.com/pypi/sh/)

The same happening when specifying version as well

Curling this address (from the log) http://pypi.tk.com/api/package/2mp4/2mp4-0.2.1.tar.gz returns 404 while curling the address http://pypi.tk.com/api/package/2mp4/ returing the following json:

{"write": true, "packages": [{"url": "https://*.s3.amazonaws.com/packages/70b6/2mp4/2mp4-0.2.1.tar.gz?Signature=***&Expires=***&AWSAccessKeyId=***", "last_modified": ****, "name": "2mp4", "version": "0.2.1", "filename": "2mp4-0.2.1.tar.gz"}, {"url": "https://***.s3.amazonaws.com/packages/78e1/2mp4/2mp4-0.1.4.tar.gz?Signature=***&Expires=***&AWSAccessKeyId=****", "last_modified": ***, "name": "2mp4", "version": "0.1.4", "filename": "2mp4-0.1.4.tar.gz"}, {"url": "https://***.s3.amazonaws.com/packages/1c84/2mp4/2mp4-0.1.3.tar.gz?Signature=****&Expires=***&AWSAccessKeyId=****", "last_modified": ***, "name": "2mp4", "version": "0.1.3", "filename": "2mp4-0.1.3.tar.gz"}]}

Additional information may assist:
I have upgraded the pypicloud from older version using the export and import tools as suggested in the docs, changes from local sql cache db to local redis db, and had to rebuild the cache index because my s3 bucket was already exists with the packages from the older version while on the new version i got an empty cache index, so i used the api call /admin/rebuild, and since then i can't download any package, no matter if its on my local repo, or needs to be fetched.

The workaround for now is switching back to redirect mode, not to cause downtime to my users.

Thanks a lot,
Let me know if there's any way I can assist.

Thanks

**Comment by stevearc** [comment] 2015-05-14 03:40
I know where the 404's are coming from. If you're using S3, pypicloud will return a 404 if you hit the download endpoint because (long story short) a bug in python makes it impossible to gracefully redirect to S3, so we just don't even try. That's a usability bug, and it should definitely give you a better indication of what's going on.

The bug that's causing your download issues is that in mirror mode I wasn't overwriting the download urls of packages that already existed in the cache. That will *only* cause problems when using S3 storage, for the reason mentioned above.

I think I have a fix in the [0.2 branch](https://github.com/mathcamp/pypicloud/tree/0.2). If you can, it'd be great if you could try that out. If not, I'll just test it as best I can locally and cut a new release.

**Comment by avihoo** [comment] 2015-05-14 07:05
Hi,

I applied your fix in the s3 file, and tried it out, and this is the response i got:

$ pip install 2mp4
You are using pip version 6.0.6, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting 2mp4
  This repository located at pypi.myhost.com is not a trusted host, if this repository is available via HTTPS it is recommend to use HTTPS instead, otherwise you may silence this warning with '--trusted-host pypi.myhost.com'.
  DEPRECATION: Implicitly allowing locations which are not hosted at a secure origin is deprecated and will require the use of --trusted-host in the future.
  HTTP error 502 while getting http://pypi.myhost.com/api/package/2mp4/2mp4-0.2.1.tar.gz (from http://pypi.myhost.com/pypi/2mp4/)
  Could not install requirement 2mp4 because of error 502 Server Error: Bad Gateway
  Could not install requirement 2mp4 because of HTTP error 502 Server Error: Bad Gateway for URL http://pypi.myhost.com/api/package/2mp4/2mp4-0.2.1.tar.gz (from http://pypi.myhost.com/pypi/2mp4/)

Please let me know if there's something else I can help with.

Thanks

**Comment by avihoo** [comment] 2015-05-14 07:14
Hi,

So I applied your changes from the 0.2 branch and tested it as follows:

1. pip install 2mp4 (without version) - successfully installed from my s3 repo

2. pip install 2mp4==0.1.4 (version which i have in cache) - successfully installed from my s3 repo

3. pip install 2mp4==0.1.3 (version which i don't have in s3 repo) - successfully fetched from fallback url, saved it to s3 repo, and installed it.

Seems to work!

Many thanks!!

**Comment by stevearc** [comment] 2015-05-14 16:05
Great! I'll cut a new release with this fix in it

**Comment by stevearc** [comment] 2015-05-14 17:04
Released as 0.2.12

**Closed by stevearc** 2015-05-14 17:04 UTC

**Comment by ARMBouhali** [comment] 2022-10-16 13:24
For my use case, I needed to set up a local PypiCloud server to save build time and bandwidth usage across many Django projects, without worrying about version changes as my requirements versions are all frozen.

With this configuration (config.ini)
    
    pypi.fallback = cache
    pypi.always_show_upstream = true
    
I get the behavior I want, which is to mirror every single required package.
